### ISSUE TITLE
FrontEnd Checklist

### ISSUE THREAD

**Issue by dominhhai** [dominhhai/dominhhai.github.io#6]
Following the [Front-End-Checklist](https://github.com/thedaviddias/Front-End-Checklist)

# Head
## Meta tag
* [ ] X-UA-Compatible: `<meta http-equiv="x-ua-compatible" content="ie=edge">`
* [ ] Canonical: `<link rel="canonical" href="http://example.com/2017/09/a-new-article-to-red.html">`

## Social meta
* [ ] FB
* [ ] Twitter

# HTML
## Best practices
* [ ] Noopener: `rel="noopener noreferrer"`

## HTML testing

# Image
## Best practices
* [ ]  Alternative text

**Comment by dominhhai** [comment]
https://developers.google.com/web/fundamentals/performance/http2/#design_and_technical_goals
https://knowledge.sakura.ad.jp/7734/
https://blog.redbox.ne.jp/http2-cdn.html
https://www.digicert.ne.jp/ssl/http2.html
https://en.wikipedia.org/wiki/HTTP/2
